server: 
    error: 
        include-message: always  
        include-binding-errors: always 
         
spring: 
     datasource: 
        driverClassName: com.mysql.cj.jdbc.Driver
        password: chelseaFC1  
        url: jdbc:mysql://localhost:3306/springTestDB
        username: root 
        
     jpa: 
         hibernate: 
            ddl-auto: create-drop 
         properties: 
             hibernate: 
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true 
     show-sql: true 
                
     mail:
         host: smtp.pepipost.com
         port: 25
         username: alihamedali
         password: alihamedali_5dcaeaed7aba371cc3e7d781d1281ccb
         
         properties:
            mail:
                smtp:
                    ssl:
                        trust: "*"
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000
